/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.text.ParseException;
import java.text.DateFormat;  
import java.text.SimpleDateFormat; 
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;

/**
 *
 * @author acer
 */
public class CancelReservation extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    int trainNumber,trainAvailableNumber,noOfACSeats,noOfGeneralSeats,acFair,generalFair,totalFair,NoOfBookedACTickets,NoOfBookedGeneralTickets;
    String trainName,date2,passengerName,passnegerPhone,status,userId,bookedDate;
    Date date;
    DefaultTableModel model ;
    String userName;
    public CancelReservation() {
        initComponents();
       reservatioDetail();
        currenTime();
    }
    public CancelReservation(String userName) {
        initComponents();
       reservatioDetail();
        currenTime();
        this.userName = userName;
        txtUserShowName.setText(userName);
    }
    public int getUserId(String userName){
        //System.out.println(userName);
        int userId=0;
        try{
       
            Connection db = DbConnector.getConnection();
            PreparedStatement pst = db.prepareStatement("select userId from user where UserName=?");
            pst.setString(1,userName);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){  
                userId =rs.getInt("userId");  
            }
            /*else{
                JOptionPane.showMessageDialog(this,"Invalid User Name or Password");
            }*/
        }
        catch(Exception ex){
            ex.printStackTrace();
        }    
         
        return userId;
    }
    public void currenTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now(); 
        String strLocalDateTime = now.toString();
        this.lblDateTime.setText(strLocalDateTime);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelDashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelReservation = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelTrains = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelSchedule = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelLogout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUserShowName = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        PanelTrains1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtTrainNumber = new app.bolivia.swing.JCTextField();
        btnCheckAvailability = new necesario.RSMaterialButtonCircle();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservation = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Train Reservation Management");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 480, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, -20, 40, 70));

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/undo.png"))); // NOI18N
        lblBack.setText("  Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel4.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDashboard.setBackground(new java.awt.Color(0, 0, 51));
        PanelDashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDashboardMouseClicked(evt);
            }
        });
        PanelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/dashboard.png"))); // NOI18N
        jLabel5.setText(" Dashboard");
        PanelDashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, -1));

        jPanel2.add(PanelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 70));

        PanelReservation.setBackground(new java.awt.Color(0, 0, 51));
        PanelReservation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelReservation.setForeground(new java.awt.Color(255, 255, 255));
        PanelReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelReservationMouseClicked(evt);
            }
        });
        PanelReservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/tickets.png"))); // NOI18N
        jLabel7.setText(" Reservation");
        PanelReservation.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel2.add(PanelReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 70));

        PanelTrains.setBackground(new java.awt.Color(0, 0, 51));
        PanelTrains.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelTrains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelTrainsMouseClicked(evt);
            }
        });
        PanelTrains.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/train.png"))); // NOI18N
        jLabel6.setText(" Trains");
        PanelTrains.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel2.add(PanelTrains, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 70));

        PanelSchedule.setBackground(new java.awt.Color(0, 0, 51));
        PanelSchedule.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelScheduleMouseClicked(evt);
            }
        });
        PanelSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/calendar.png"))); // NOI18N
        jLabel9.setText(" Train Schedule");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        PanelSchedule.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(PanelSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 260, 70));

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/report.png"))); // NOI18N
        jLabel8.setText(" Reports");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 260, 70));

        PanelLogout.setBackground(new java.awt.Color(0, 0, 51));
        PanelLogout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelLogoutMouseClicked(evt);
            }
        });
        PanelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/icons8-logout-30.png"))); // NOI18N
        jLabel3.setText(" Logout");
        PanelLogout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, -1));

        jPanel2.add(PanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 260, 70));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/User.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        txtUserShowName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtUserShowName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserShowName.setText("--");
        jPanel2.add(txtUserShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));

        lblDateTime.setBackground(new java.awt.Color(0, 0, 102));
        lblDateTime.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setText("--");
        lblDateTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDateTimeMouseClicked(evt);
            }
        });
        jPanel2.add(lblDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        PanelTrains1.setBackground(new java.awt.Color(0, 0, 51));
        PanelTrains1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelTrains1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelTrains1MouseClicked(evt);
            }
        });
        PanelTrains1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/train.png"))); // NOI18N
        jLabel14.setText(" Cancel Reservation");
        PanelTrains1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(PanelTrains1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Search");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 52, -1, 30));

        txtTrainNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtTrainNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtTrainNumber.setForeground(new java.awt.Color(0, 0, 0));
        txtTrainNumber.setPlaceholder("Enter the Ticket Number");
        txtTrainNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrainNumberActionPerformed(evt);
            }
        });
        jPanel11.add(txtTrainNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, -1));

        btnCheckAvailability.setBackground(new java.awt.Color(0, 0, 0));
        btnCheckAvailability.setText("Delete Reservation");
        btnCheckAvailability.setAlignmentY(0.4F);
        btnCheckAvailability.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAvailabilityActionPerformed(evt);
            }
        });
        jPanel11.add(btnCheckAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 200, 50));

        tblReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Passenger Name", "Train Name", "Date", "No Of AC Ticket Booked", "No Of General Tickets Booked", "Status"
            }
        ));
        tblReservation.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tblReservation.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblReservation.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblReservation.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblReservation.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblReservation.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblReservation.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblReservation.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblReservation.setFuenteHead(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tblReservation.setRowHeight(25);
        tblReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReservation);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 940, 360));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 950, 660));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 1080, 760));

        setSize(new java.awt.Dimension(1300, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnCheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAvailabilityActionPerformed
      
    }//GEN-LAST:event_btnCheckAvailabilityActionPerformed
    
   
 
    private void PanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDashboardMouseClicked
        Dashboard window = new Dashboard();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelDashboardMouseClicked

    private void PanelReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservationMouseClicked
        CancelReservation window = new CancelReservation();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelReservationMouseClicked

    private void PanelTrainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTrainsMouseClicked
        TrainManager window = new TrainManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelTrainsMouseClicked

    private void PanelScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelScheduleMouseClicked
        TrainScheduleManager window = new TrainScheduleManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelScheduleMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        TrainScheduleManager window = new TrainScheduleManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void PanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLogoutMouseClicked
        Login window = new Login();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelLogoutMouseClicked

    private void tblReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservationMouseClicked
        int rowNo = tblReservation.getSelectedRow();
        TableModel model = tblReservation.getModel();
        int column=0;
        this.txtTrainNumber.setText(model.getValueAt(rowNo, column).toString());
    }//GEN-LAST:event_tblReservationMouseClicked

    private void lblDateTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDateTimeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDateTimeMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here: private void PanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {
            Dashboard window = new Dashboard();
            window.show();
            this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtTrainNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrainNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrainNumberActionPerformed

    private void PanelTrains1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTrains1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelTrains1MouseClicked
    
    public void reservatioDetail(){
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select r.ticketNumber as RticketNumber,r.PassengerName as Rname,t.trainName as RtrainName,R.ScheduleDate as RDate,r.NoOfBookedACTickets as RBookedAC,r.NoOfBookedGeneralTickets as RBookedGeneral,r.status as Rstatus "
                    + "from reservation as r,trainlist as t where t.trainNumber=r.trainNumber order by  TicketNumber DESC");
            
            while (rs.next()){
                trainNumber = rs.getInt("RticketNumber");
                passengerName = rs.getString("Rname");
                trainName = rs.getString("RtrainName");
                bookedDate = rs.getString("RDate");
                NoOfBookedACTickets = rs.getInt("RBookedAC");
                NoOfBookedGeneralTickets = rs.getInt("RBookedGeneral");
                status = rs.getString("Rstatus");
                
                Object[] row = {trainNumber,passengerName,trainName,bookedDate,NoOfBookedACTickets,NoOfBookedGeneralTickets,status};
                model = (DefaultTableModel)tblReservation.getModel();
                model.addRow(row);
                
                
            }
            
            
        }
        catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JPanel PanelReservation;
    private javax.swing.JPanel PanelSchedule;
    private javax.swing.JPanel PanelTrains;
    private javax.swing.JPanel PanelTrains1;
    private necesario.RSMaterialButtonCircle btnCheckAvailability;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDateTime;
    private rojeru_san.complementos.RSTableMetro tblReservation;
    private app.bolivia.swing.JCTextField txtTrainNumber;
    private javax.swing.JLabel txtUserShowName;
    // End of variables declaration//GEN-END:variables
}
