/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Color;
import java.sql.Connection;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author acer
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    //Login lg = new Login();
    int trainNumber,trainAvailableNumber,trainCount,bookingCount,noOfACSeats,noOfGeneralSeats,ticketNumber;
    String trainName,source,destination,trainAvailableDay;
    Double generalFair,acfair;
    String userName;
    DefaultTableModel model ;
    public Dashboard() {
        initComponents();
        TrainAvailableTableDetails();
        CountTrain();
        CountBookings();
        TrainSheetTableDetails();
        currenTime();
        TrainBookingDetails();
        
        
    }
    
    public Dashboard(String uName) {
        
        initComponents();
        TrainAvailableTableDetails();
        CountTrain();
        CountBookings();
        TrainSheetTableDetails();
        currenTime();
        TrainBookingDetails();
        this.userName = uName;
        txtUserShowName.setText(userName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelReservation = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelTrains = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelTrainSchedule = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelLogOut = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserShowName = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrainAvailable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTrainDetails = new rojeru_san.complementos.RSTableMetro();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBoookings = new rojeru_san.complementos.RSTableMetro();
        jLabel15 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        countTrain = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panel5 = new java.awt.Panel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panel6 = new java.awt.Panel();
        jLabel17 = new javax.swing.JLabel();
        lblCountBooking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Railway Reservation System ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 480, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, -20, 40, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(0, 0, 51));
        Dashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/dashboard.png"))); // NOI18N
        jLabel5.setText(" Dashboard");
        Dashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, -1));

        jPanel2.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 70));

        PanelReservation.setBackground(new java.awt.Color(0, 0, 51));
        PanelReservation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelReservation.setForeground(new java.awt.Color(255, 255, 255));
        PanelReservation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelReservationMouseMoved(evt);
            }
        });
        PanelReservation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelReservationFocusGained(evt);
            }
        });
        PanelReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelReservationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelReservationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelReservationMouseExited(evt);
            }
        });
        PanelReservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/tickets.png"))); // NOI18N
        jLabel7.setText(" Reservation");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        PanelReservation.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel2.add(PanelReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 70));

        PanelTrains.setBackground(new java.awt.Color(0, 0, 51));
        PanelTrains.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelTrains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelTrainsMouseClicked(evt);
            }
        });
        PanelTrains.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/train.png"))); // NOI18N
        jLabel6.setText(" Trains");
        PanelTrains.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel2.add(PanelTrains, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 70));

        PanelTrainSchedule.setBackground(new java.awt.Color(0, 0, 51));
        PanelTrainSchedule.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelTrainSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelTrainScheduleMouseClicked(evt);
            }
        });
        PanelTrainSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/calendar.png"))); // NOI18N
        jLabel9.setText(" Train Schedule");
        PanelTrainSchedule.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(PanelTrainSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 70));

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/report.png"))); // NOI18N
        jLabel8.setText(" Reports");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 260, 70));

        PanelLogOut.setBackground(new java.awt.Color(0, 0, 51));
        PanelLogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelLogOutMouseClicked(evt);
            }
        });
        PanelLogOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/icons8-logout-30.png"))); // NOI18N
        jLabel3.setText(" Logout");
        PanelLogOut.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, -1));

        jPanel2.add(PanelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 260, 70));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/User.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        txtUserShowName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtUserShowName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserShowName.setText("-");
        jPanel2.add(txtUserShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));

        lblDateTime.setBackground(new java.awt.Color(0, 0, 102));
        lblDateTime.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setText("--");
        lblDateTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDateTimeMouseClicked(evt);
            }
        });
        jPanel2.add(lblDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTrainAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train Number", "Date", "AC Sheets Available", "AC Ticket Price", "General Sheets Available", "General Ticket Price"
            }
        ));
        tblTrainAvailable.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tblTrainAvailable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblTrainAvailable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblTrainAvailable.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblTrainAvailable.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblTrainAvailable.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblTrainAvailable.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblTrainAvailable.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblTrainAvailable.setFuenteHead(new java.awt.Font("Serif", 1, 16)); // NOI18N
        tblTrainAvailable.setRowHeight(25);
        jScrollPane1.setViewportView(tblTrainAvailable);
        if (tblTrainAvailable.getColumnModel().getColumnCount() > 0) {
            tblTrainAvailable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 980, 150));

        tblTrainDetails.setForeground(new java.awt.Color(0, 0, 0));
        tblTrainDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train Number", "Train Name", "Source", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrainDetails.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tblTrainDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblTrainDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblTrainDetails.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblTrainDetails.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblTrainDetails.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblTrainDetails.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblTrainDetails.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblTrainDetails.setFuenteHead(new java.awt.Font("Serif", 1, 16)); // NOI18N
        tblTrainDetails.setRowHeight(25);
        tblTrainDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrainDetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTrainDetails);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 470, 140));

        jLabel18.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Available Sheet for Trains");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Our Trains");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        panel3.setBackground(new java.awt.Color(204, 204, 255));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBoookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Train Number", "Date", "Passenger Name"
            }
        ));
        tblBoookings.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tblBoookings.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblBoookings.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblBoookings.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblBoookings.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblBoookings.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblBoookings.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblBoookings.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblBoookings.setFuenteHead(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tblBoookings.setRowHeight(25);
        tblBoookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoookingsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBoookings);
        if (tblBoookings.getColumnModel().getColumnCount() > 0) {
            tblBoookings.getColumnModel().getColumn(2).setResizable(false);
        }

        panel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 750, 150));

        jLabel15.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Recent Bookings");
        panel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel3.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 880, 230));

        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("No Of Booking");
        panel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("No Of Trains");
        panel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -1, 120, 30));

        panel4.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 30));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countTrain.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        countTrain.setForeground(new java.awt.Color(204, 0, 0));
        countTrain.setText("0");
        panel2.add(countTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 60, 80));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/countJpg.png"))); // NOI18N
        panel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 140, 120));

        panel4.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, 90));

        panel5.setBackground(new java.awt.Color(0, 0, 102));
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("No Of Booking");
        panel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("No Of BOOKINGS");
        panel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 30));
        jLabel22.getAccessibleContext().setAccessibleName("No Of Bookings");

        panel4.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 180, 30));

        panel6.setBackground(new java.awt.Color(255, 255, 255));
        panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/Ticket.png"))); // NOI18N
        panel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -20, 170, 120));

        lblCountBooking.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        lblCountBooking.setForeground(new java.awt.Color(102, 0, 0));
        lblCountBooking.setText("0");
        panel6.add(lblCountBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 70, 80));

        panel4.add(panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 180, 90));

        jPanel3.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 420, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 1080, 760));

        setSize(new java.awt.Dimension(1300, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public int getUserId(String userName){
        int userId=0;
        try{
       
            Connection db = DbConnector.getConnection();
            PreparedStatement pst = db.prepareStatement("select userId from user where UserName=?");
            pst.setString(1,userName);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                
                userId =rs.getInt("userId");;
                this.dispose();
                
            }
            /*else{
                JOptionPane.showMessageDialog(this,"Invalid User Name or Password");
            }*/
        }
        catch(Exception ex){
            ex.printStackTrace();
        }    
         
        return userId;
    }
    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
       
    }//GEN-LAST:event_DashboardMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void PanelTrainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTrainsMouseClicked
        TrainManager window = new TrainManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelTrainsMouseClicked

    private void PanelReservationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservationMouseMoved
       
        
    }//GEN-LAST:event_PanelReservationMouseMoved

    private void PanelReservationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelReservationFocusGained
        
    }//GEN-LAST:event_PanelReservationFocusGained

    private void PanelReservationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservationMouseEntered
         //PanelReservation.setBackground(Color.red);
    }//GEN-LAST:event_PanelReservationMouseEntered

    private void PanelReservationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservationMouseExited
         //PanelReservation.setBackground(color.);
    }//GEN-LAST:event_PanelReservationMouseExited

    private void PanelTrainScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTrainScheduleMouseClicked
        // TODO add your handling code here:
         TrainScheduleManager window = new TrainScheduleManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelTrainScheduleMouseClicked

    private void PanelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLogOutMouseClicked
        Login window = new Login();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelLogOutMouseClicked

    private void tblTrainDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrainDetailsMouseClicked
      
    }//GEN-LAST:event_tblTrainDetailsMouseClicked

    private void lblDateTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDateTimeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDateTimeMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void tblBoookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoookingsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBoookingsMouseClicked

    private void PanelReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservationMouseClicked
        Reservation window = new Reservation(userName);
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelReservationMouseClicked
    public void currenTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now(); 
        String strLocalDateTime = now.toString();
        this.lblDateTime.setText(strLocalDateTime);
    }
    public void CountTrain(){
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select count(*) from trainList");
            
            while (rs.next()){
              trainCount = rs.getInt("count(*)");
              String strtrainCount= Integer.toString(trainCount);
              this.countTrain.setText(strtrainCount);
                
            }
            
            
        } 
      
        
        catch (Exception ex) {
           ex.printStackTrace();
        }
    
        
    }
    
    public void CountBookings(){
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select count(*) from reservation");
            
            while (rs.next()){
              bookingCount = rs.getInt("count(*)");
              String strtrainCount= Integer.toString(bookingCount);
              this.lblCountBooking.setText(strtrainCount);
                
            }
            
            
        } 
      
        
        catch (Exception ex) {
           ex.printStackTrace();
        }
    
        
    }
    public void TrainAvailableTableDetails(){
        
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select TrainNumber,TrainName,Source,Destination from trainList");
            
            while (rs.next()){
              trainNumber = rs.getInt("TrainNumber");
              trainName = rs.getString("TrainName");
              source = rs.getString("Source");
              destination = rs.getString("Destination");
              
                
                Object[] row = {trainNumber,trainName,source,destination};
                model = (DefaultTableModel)tblTrainDetails.getModel();
                model.addRow(row);
                
                
            }
            
            
        } 
      
        
        catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    
    public void TrainSheetTableDetails(){
        
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select ts.TrainNumber,ts.ScheduleDate,ts.NoOfACSeats,tl.ACTicketFair,ts.NoOfGeneralSeats,tl.GeneralTicketFair from trainstatus as ts,trainList as tl where ts.trainNumber=tl.trainNumber");
            
            while (rs.next()){
              trainNumber = rs.getInt("TrainNumber");
              String ScheduleDate = rs.getString("ScheduleDate");
              noOfACSeats = rs.getInt("NoOfACSeats");
              Double acTicketFair = rs.getDouble("ACTicketFair");
              noOfGeneralSeats = rs.getInt("NoOfGeneralSeats");
              Double generalTicketFair = rs.getDouble("GeneralTicketFair");
              
                
                Object[] row = {trainNumber,ScheduleDate,noOfACSeats,acTicketFair,noOfGeneralSeats,generalTicketFair};
                model = (DefaultTableModel)tblTrainAvailable.getModel();
                model.addRow(row);
                
                
            }
            
            
        } 
      
        
        catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    
    public void TrainBookingDetails(){
        
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select TicketNumber,TrainNumber,ScheduleDate,PassengerName from reservation");
            
            while (rs.next()){
              trainNumber = rs.getInt("TicketNumber");
              ticketNumber = rs.getInt("TrainNumber");
              String scheduleDate = rs.getString("ScheduleDate");
              String PassengerName = rs.getString("PassengerName");
              
                
                Object[] row = {trainNumber,ticketNumber,scheduleDate,PassengerName};
                model = (DefaultTableModel)tblBoookings.getModel();
                model.addRow(row);
                
                
            }
            
            
        } 
      
        
        catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel PanelLogOut;
    private javax.swing.JPanel PanelReservation;
    private javax.swing.JPanel PanelTrainSchedule;
    private javax.swing.JPanel PanelTrains;
    private javax.swing.JLabel countTrain;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCountBooking;
    private javax.swing.JLabel lblDateTime;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private rojeru_san.complementos.RSTableMetro tblBoookings;
    private rojeru_san.complementos.RSTableMetro tblTrainAvailable;
    private rojeru_san.complementos.RSTableMetro tblTrainDetails;
    private javax.swing.JLabel txtUserShowName;
    // End of variables declaration//GEN-END:variables
}
