/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.text.ParseException;
import java.text.DateFormat;  
import java.text.SimpleDateFormat; 
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;

/**
 *
 * @author acer
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    int trainNumber,trainAvailableNumber,noOfACSeats,noOfGeneralSeats,acFair,generalFair,totalFair,NoOfBookedACTickets,NoOfBookedGeneralTickets;
    String trainName,date2,passengerName,passnegerPhone,status,userId,bookedDate;
    Date date;
    DefaultTableModel model ;
    String userName;
    public Reservation() {
        initComponents();
        TrainTableDetails();
        currenTime();
    }
    public Reservation(String userName) {
        initComponents();
        TrainTableDetails();
        currenTime();
        this.userName = userName;
        txtUserShowName.setText(userName);
    }
    public int getUserId(String userName){
        //System.out.println(userName);
        int userId=0;
        try{
       
            Connection db = DbConnector.getConnection();
            PreparedStatement pst = db.prepareStatement("select userId from user where UserName=?");
            pst.setString(1,userName);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){  
                userId =rs.getInt("userId");  
            }
            /*else{
                JOptionPane.showMessageDialog(this,"Invalid User Name or Password");
            }*/
        }
        catch(Exception ex){
            ex.printStackTrace();
        }    
         
        return userId;
    }
    public void currenTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now(); 
        String strLocalDateTime = now.toString();
        this.lblDateTime.setText(strLocalDateTime);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelDashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelReservation = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelTrains = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelSchedule = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelLogout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUserShowName = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtBookedDate = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtReservePassengerName = new app.bolivia.swing.JCTextField();
        jLabel18 = new javax.swing.JLabel();
        txtReservePassengerPhone = new app.bolivia.swing.JCTextField();
        jLabel19 = new javax.swing.JLabel();
        txtReservationNoOfGeneralTickets = new app.bolivia.swing.JCTextField();
        btnReservation = new necesario.RSMaterialButtonCircle();
        lblTotalFair = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnReservationCancel = new necesario.RSMaterialButtonCircle();
        jLabel26 = new javax.swing.JLabel();
        txtReservationNoOfACTickets = new app.bolivia.swing.JCTextField();
        jLabel27 = new javax.swing.JLabel();
        lblACTicketFair = new javax.swing.JLabel();
        txtReservationTrainNumber1 = new app.bolivia.swing.JCTextField();
        jLabel28 = new javax.swing.JLabel();
        lblGeneralTicketFair = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTrainNumber = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailability = new rojeru_san.complementos.RSTableMetro();
        btnCheckAvailability = new necesario.RSMaterialButtonCircle();
        btnAvailabilityReset = new necesario.RSMaterialButtonCircle();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTrainSearch1 = new rojeru_san.complementos.RSTableMetro();
        dateScheduleDate1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Train Reservation Management");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 480, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, -20, 40, 70));

        lblBack.setBackground(new java.awt.Color(255, 255, 255));
        lblBack.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/undo.png"))); // NOI18N
        lblBack.setText("  Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel4.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDashboard.setBackground(new java.awt.Color(0, 0, 51));
        PanelDashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDashboardMouseClicked(evt);
            }
        });
        PanelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/dashboard.png"))); // NOI18N
        jLabel5.setText(" Dashboard");
        PanelDashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, -1));

        jPanel2.add(PanelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 70));

        PanelReservation.setBackground(new java.awt.Color(0, 0, 51));
        PanelReservation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelReservation.setForeground(new java.awt.Color(255, 255, 255));
        PanelReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelReservationMouseClicked(evt);
            }
        });
        PanelReservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/tickets.png"))); // NOI18N
        jLabel7.setText(" Reservation");
        PanelReservation.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel2.add(PanelReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 70));

        PanelTrains.setBackground(new java.awt.Color(0, 0, 51));
        PanelTrains.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelTrains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelTrainsMouseClicked(evt);
            }
        });
        PanelTrains.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/train.png"))); // NOI18N
        jLabel6.setText(" Trains");
        PanelTrains.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        jPanel2.add(PanelTrains, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 70));

        PanelSchedule.setBackground(new java.awt.Color(0, 0, 51));
        PanelSchedule.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelScheduleMouseClicked(evt);
            }
        });
        PanelSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/calendar.png"))); // NOI18N
        jLabel9.setText(" Train Schedule");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        PanelSchedule.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(PanelSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 70));

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/report.png"))); // NOI18N
        jLabel8.setText(" Reports");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 260, 70));

        PanelLogout.setBackground(new java.awt.Color(0, 0, 51));
        PanelLogout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        PanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelLogoutMouseClicked(evt);
            }
        });
        PanelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/icons8-logout-30.png"))); // NOI18N
        jLabel3.setText(" Logout");
        PanelLogout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, -1));

        jPanel2.add(PanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 260, 70));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Train/User.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        txtUserShowName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtUserShowName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserShowName.setText("--");
        jPanel2.add(txtUserShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));

        lblDateTime.setBackground(new java.awt.Color(0, 0, 102));
        lblDateTime.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setText("--");
        lblDateTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDateTimeMouseClicked(evt);
            }
        });
        jPanel2.add(lblDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Book Your Seat ");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtBookedDate.setEditable(false);
        txtBookedDate.setBackground(new java.awt.Color(204, 204, 255));
        txtBookedDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtBookedDate.setForeground(new java.awt.Color(0, 0, 0));
        txtBookedDate.setPlaceholder("Booking Date");
        txtBookedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookedDateActionPerformed(evt);
            }
        });
        jPanel10.add(txtBookedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Date");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Passenger Name");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        txtReservePassengerName.setBackground(new java.awt.Color(204, 204, 255));
        txtReservePassengerName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtReservePassengerName.setForeground(new java.awt.Color(0, 0, 0));
        txtReservePassengerName.setPlaceholder("Enter the Passenger Name");
        txtReservePassengerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservePassengerNameActionPerformed(evt);
            }
        });
        jPanel10.add(txtReservePassengerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Phone Number");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        txtReservePassengerPhone.setBackground(new java.awt.Color(204, 204, 255));
        txtReservePassengerPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtReservePassengerPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtReservePassengerPhone.setPlaceholder("Enter the Passenger Phone");
        txtReservePassengerPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservePassengerPhoneActionPerformed(evt);
            }
        });
        jPanel10.add(txtReservePassengerPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("No Of General Tickets");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        txtReservationNoOfGeneralTickets.setBackground(new java.awt.Color(204, 204, 255));
        txtReservationNoOfGeneralTickets.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtReservationNoOfGeneralTickets.setForeground(new java.awt.Color(0, 0, 0));
        txtReservationNoOfGeneralTickets.setText("0");
        txtReservationNoOfGeneralTickets.setPlaceholder("Enter the No of General Tickets need ");
        txtReservationNoOfGeneralTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReservationNoOfGeneralTicketsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReservationNoOfGeneralTicketsMouseExited(evt);
            }
        });
        txtReservationNoOfGeneralTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationNoOfGeneralTicketsActionPerformed(evt);
            }
        });
        txtReservationNoOfGeneralTickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReservationNoOfGeneralTicketsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReservationNoOfGeneralTicketsKeyReleased(evt);
            }
        });
        jPanel10.add(txtReservationNoOfGeneralTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        btnReservation.setBackground(new java.awt.Color(0, 0, 0));
        btnReservation.setText("Make Reservation");
        btnReservation.setAlignmentY(0.4F);
        btnReservation.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });
        jPanel10.add(btnReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 200, 50));

        lblTotalFair.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        lblTotalFair.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalFair.setText("_____________");
        jPanel10.add(lblTotalFair, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, -1));

        jLabel23.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Total Fair");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel25.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Train Number");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        btnReservationCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnReservationCancel.setText("Cancel");
        btnReservationCancel.setAlignmentY(0.4F);
        btnReservationCancel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnReservationCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationCancelActionPerformed(evt);
            }
        });
        jPanel10.add(btnReservationCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 170, 50));

        jLabel26.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("No Of AC Tickets");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtReservationNoOfACTickets.setBackground(new java.awt.Color(204, 204, 255));
        txtReservationNoOfACTickets.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtReservationNoOfACTickets.setForeground(new java.awt.Color(0, 0, 0));
        txtReservationNoOfACTickets.setText("0");
        txtReservationNoOfACTickets.setPlaceholder("Enter the No of AC Tickets need");
        txtReservationNoOfACTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationNoOfACTicketsActionPerformed(evt);
            }
        });
        txtReservationNoOfACTickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReservationNoOfACTicketsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReservationNoOfACTicketsKeyReleased(evt);
            }
        });
        jPanel10.add(txtReservationNoOfACTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("AC _Per Ticket Fair ");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        lblACTicketFair.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        lblACTicketFair.setForeground(new java.awt.Color(0, 0, 0));
        lblACTicketFair.setText("_____________");
        jPanel10.add(lblACTicketFair, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

        txtReservationTrainNumber1.setEditable(false);
        txtReservationTrainNumber1.setBackground(new java.awt.Color(204, 204, 255));
        txtReservationTrainNumber1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtReservationTrainNumber1.setForeground(new java.awt.Color(0, 0, 0));
        txtReservationTrainNumber1.setPlaceholder("Train Number ");
        txtReservationTrainNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationTrainNumber1ActionPerformed(evt);
            }
        });
        jPanel10.add(txtReservationTrainNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel28.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("General _Per Ticket Fair ");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        lblGeneralTicketFair.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        lblGeneralTicketFair.setForeground(new java.awt.Color(0, 0, 0));
        lblGeneralTicketFair.setText("_____________");
        jPanel10.add(lblGeneralTicketFair, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 940, 360));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Train Number");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Date");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        txtTrainNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtTrainNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtTrainNumber.setForeground(new java.awt.Color(0, 0, 0));
        txtTrainNumber.setPlaceholder("Enter the Train Number ");
        txtTrainNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrainNumberActionPerformed(evt);
            }
        });
        jPanel11.add(txtTrainNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        tblAvailability.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Train Number", "Train Name", "Available General Tickets", "Available AC Tickets"
            }
        ));
        tblAvailability.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tblAvailability.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblAvailability.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblAvailability.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblAvailability.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblAvailability.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblAvailability.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblAvailability.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblAvailability.setFuenteHead(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tblAvailability.setRowHeight(25);
        tblAvailability.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAvailabilityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAvailability);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 900, 80));

        btnCheckAvailability.setBackground(new java.awt.Color(0, 0, 0));
        btnCheckAvailability.setText("Check Availability");
        btnCheckAvailability.setAlignmentY(0.4F);
        btnCheckAvailability.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAvailabilityActionPerformed(evt);
            }
        });
        jPanel11.add(btnCheckAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 200, 50));

        btnAvailabilityReset.setBackground(new java.awt.Color(0, 0, 0));
        btnAvailabilityReset.setText("Reset");
        btnAvailabilityReset.setAlignmentY(0.4F);
        btnAvailabilityReset.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAvailabilityReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailabilityResetActionPerformed(evt);
            }
        });
        jPanel11.add(btnAvailabilityReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 160, 50));

        tblTrainSearch1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train Number", "Train Name"
            }
        ));
        tblTrainSearch1.setColorBackgoundHead(new java.awt.Color(0, 0, 102));
        tblTrainSearch1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblTrainSearch1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblTrainSearch1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblTrainSearch1.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblTrainSearch1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tblTrainSearch1.setFuenteFilas(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblTrainSearch1.setFuenteFilasSelect(new java.awt.Font("Serif", 1, 14)); // NOI18N
        tblTrainSearch1.setFuenteHead(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tblTrainSearch1.setRowHeight(25);
        tblTrainSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrainSearch1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTrainSearch1);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 400, 170));

        dateScheduleDate1.setBackground(new java.awt.Color(255, 255, 255));
        dateScheduleDate1.setForeground(new java.awt.Color(255, 255, 255));
        dateScheduleDate1.setDateFormatString("yyyy-MM-dd");
        jPanel11.add(dateScheduleDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 950, 300));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 1080, 760));

        setSize(new java.awt.Dimension(1300, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTrainNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrainNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrainNumberActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Do you really want to continue add train reservation", "Confirmation message", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if(makeReservaton()==true){
                JOptionPane.showMessageDialog(this,"Reservation Sucessfully Added");
               
                
            }
            else{
                JOptionPane.showMessageDialog(this,"Something went worng with the train reservation Please try again");
            }
        }
        else{
                reset();
        }
    }//GEN-LAST:event_btnReservationActionPerformed
    public void ticketFair(){
        try{
        NoOfBookedACTickets = Integer.parseInt(this.txtReservationNoOfACTickets.getText());
        NoOfBookedGeneralTickets = Integer.parseInt(this.txtReservationNoOfGeneralTickets.getText());
        acFair = Integer.parseInt(this.lblACTicketFair.getText());
        generalFair = Integer.parseInt(this.lblGeneralTicketFair.getText());
        
        int totalFair=0;
        totalFair = (NoOfBookedACTickets*acFair)+(generalFair*NoOfBookedGeneralTickets);
        //System.out.println(totalFair);
        //System.out.println(acFair);
        //System.out.println(generalFair);
        //System.out.println(NoOfBookedACTickets);
        //System.out.println(NoOfBookedGeneralTickets);
        String stotalFair =Integer.toString(totalFair);
        this.lblTotalFair.setText(stotalFair);
        }
        catch(NumberFormatException ex){
            
        }
    }
    public boolean makeReservaton(){
       
        boolean isReservation=false;
        trainNumber = Integer.parseInt(this.txtTrainNumber.getText());
        bookedDate = this.txtBookedDate.getText();
        passengerName = this.txtReservePassengerName.getText();
        passnegerPhone = this.txtReservePassengerPhone.getText();
        NoOfBookedACTickets = Integer.parseInt(this.txtReservationNoOfACTickets.getText());
        NoOfBookedGeneralTickets = Integer.parseInt(this.txtReservationNoOfGeneralTickets.getText());
        acFair = Integer.parseInt(this.lblACTicketFair.getText());
        generalFair = Integer.parseInt(this.lblGeneralTicketFair.getText());
        String sql = "insert into reservation(PassengerName,PassengerPhone,NoOfBookedACTickets,NoOfBookedGeneralTickets,TotalFair,Status,TrainNumber,ScheduleDate,UserId) values(?,?,?,?,?,?,?,?,?)";
        Connection db = DbConnector.getConnection();
        PreparedStatement pst;
        try {
            pst = db.prepareStatement(sql);
            pst.setString(1, passengerName);
            pst.setString(2, passnegerPhone);
            pst.setInt(3, NoOfBookedACTickets);
            pst.setInt(4, NoOfBookedGeneralTickets);
            totalFair = (NoOfBookedACTickets*acFair)+(generalFair*NoOfBookedGeneralTickets);
            pst.setInt(5, totalFair);
            //check here
            String status ="confirmed";
            pst.setString(6, status);
            pst.setInt(7, trainNumber);
            pst.setString(8, bookedDate);
            System.out.println(userId);
            int userId =getUserId(userName);
            pst.setInt(9, userId);
           
            //userId here
            //pst.setString(9, status);
            int rowCount = pst.executeUpdate();
            
            if(rowCount>0){
                   isReservation=true;
                   reset();
                   
            }
            else{
                reset();
            }
            
        } 
       
        catch (Exception ex) {
           ex.printStackTrace();
        }
        
    
        return isReservation;
    }
    private void txtBookedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookedDateActionPerformed

    private void txtReservePassengerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservePassengerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservePassengerNameActionPerformed

    private void txtReservePassengerPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservePassengerPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservePassengerPhoneActionPerformed

    private void txtReservationNoOfGeneralTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationNoOfGeneralTicketsActionPerformed
            ticketFair();
    }//GEN-LAST:event_txtReservationNoOfGeneralTicketsActionPerformed

    private void btnReservationCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationCancelActionPerformed
        
    }//GEN-LAST:event_btnReservationCancelActionPerformed

    private void btnCheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAvailabilityActionPerformed
        if(checkAvailability()==true){
                //JOptionPane.showMessageDialog(this,"");
            }
        else{
                JOptionPane.showMessageDialog(this,"There is no train seats available that day");
        }
    }//GEN-LAST:event_btnCheckAvailabilityActionPerformed
    
    public boolean checkAvailability(){
        boolean isCheck=false;
        trainNumber = Integer.parseInt(this.txtTrainNumber.getText());
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date =sdf.format(dateScheduleDate1.getDate());
        
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            String query = "select ts.ScheduleDate,ts.trainnumber,tl.trainname,ts.NoOfACSeats,ts.NoOfGeneralSeats from trainstatus as ts,trainList as tl where  ts.trainnumber=? AND ts.ScheduleDate=? AND ts.trainnumber=tl.trainnumber";
            
            PreparedStatement stmt = db.prepareStatement(query);
            stmt.setInt(1,trainNumber);
            stmt.setString(2,date);
            
            
            try (ResultSet rs = stmt.executeQuery()){
                //System.out.println(trainNumber);
                while (rs.next()){
                date2 = rs.getString("ScheduleDate");
                trainNumber = rs.getInt("trainnumber");
                trainName = rs.getString("trainname");
                noOfACSeats = rs.getInt("NoOfACSeats");
                noOfGeneralSeats = rs.getInt("NoOfGeneralSeats");
                Object[] row = {date2,trainNumber,trainName,noOfACSeats,noOfGeneralSeats};
                clearTrainAvailable();
                model = (DefaultTableModel)tblAvailability.getModel();
                model.addRow(row);
                isCheck=true;

                }
                
            }
        }

        catch (Exception ex) {
           ex.printStackTrace();
        }
        return isCheck;
    }
    private void btnAvailabilityResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailabilityResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvailabilityResetActionPerformed
    public void ClearTrainTableDetails(){
        DefaultTableModel model = (DefaultTableModel)tblAvailability.getModel();
        model.setRowCount(0);
        reset();
        
    }
    
    public void reset(){
        this.txtTrainNumber.setText("");
        this.dateScheduleDate1.setDate(null);
        
    }
    private void PanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDashboardMouseClicked
        Dashboard window = new Dashboard();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelDashboardMouseClicked

    private void PanelReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReservationMouseClicked
        Reservation window = new Reservation();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelReservationMouseClicked

    private void PanelTrainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTrainsMouseClicked
        TrainManager window = new TrainManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelTrainsMouseClicked

    private void PanelScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelScheduleMouseClicked
        TrainScheduleManager window = new TrainScheduleManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelScheduleMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        TrainScheduleManager window = new TrainScheduleManager();
        window.show();
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void PanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLogoutMouseClicked
        Login window = new Login();
        window.show();
        this.dispose();
    }//GEN-LAST:event_PanelLogoutMouseClicked

    private void txtReservationNoOfACTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationNoOfACTicketsActionPerformed
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfACTicketsActionPerformed

    private void tblTrainSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrainSearch1MouseClicked
        int rowNo = tblTrainSearch1.getSelectedRow();
        TableModel model = tblTrainSearch1.getModel();
        int column=0;
        this.txtTrainNumber.setText(model.getValueAt(rowNo, column).toString());
    }//GEN-LAST:event_tblTrainSearch1MouseClicked

    private void txtReservationTrainNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationTrainNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationTrainNumber1ActionPerformed

    private void tblAvailabilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAvailabilityMouseClicked
        try 
        {
            int rowNo = tblAvailability.getSelectedRow();
            TableModel model = tblAvailability.getModel();
            int column=0;
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(rowNo, column));
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
            String strDate = dateFormat.format(date);  
            this.txtBookedDate.setText(strDate);
            this.txtReservationTrainNumber1.setText(model.getValueAt(rowNo, column+1).toString());
            trainNumber=Integer.parseInt(txtTrainNumber.getText());
            //trainNumber = Integer.parseInt(this.txtTrainNumber.getText());
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            String query = "select ACTicketFair,GeneralTicketFair from trainlist where trainNumber=?";
            
            PreparedStatement stmt = db.prepareStatement(query);
            stmt.setInt(1,trainNumber);
   
            
            try (ResultSet rs = stmt.executeQuery()){
                //System.out.println(trainNumber);
                while (rs.next()){
              
                acFair = rs.getInt("ACTicketFair");
                generalFair = rs.getInt("GeneralTicketFair");
                String stracFair= Integer. toString(acFair);
                String strGeneralFair= Integer. toString(generalFair);
                this.lblACTicketFair.setText(stracFair);
                 this.lblGeneralTicketFair.setText(strGeneralFair);


                }
                
            }
        }

        catch (Exception ex) {
           ex.printStackTrace();
        }
     
    
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
        
       
    }//GEN-LAST:event_tblAvailabilityMouseClicked

    private void txtReservationNoOfGeneralTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReservationNoOfGeneralTicketsMouseClicked
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfGeneralTicketsMouseClicked

    private void txtReservationNoOfGeneralTicketsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReservationNoOfGeneralTicketsKeyPressed
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfGeneralTicketsKeyPressed

    private void txtReservationNoOfGeneralTicketsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReservationNoOfGeneralTicketsMouseExited
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfGeneralTicketsMouseExited

    private void txtReservationNoOfGeneralTicketsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReservationNoOfGeneralTicketsKeyReleased
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfGeneralTicketsKeyReleased

    private void txtReservationNoOfACTicketsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReservationNoOfACTicketsKeyReleased
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfACTicketsKeyReleased

    private void txtReservationNoOfACTicketsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReservationNoOfACTicketsKeyPressed
        ticketFair();
    }//GEN-LAST:event_txtReservationNoOfACTicketsKeyPressed

    private void lblDateTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDateTimeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDateTimeMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here: private void PanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {
            Dashboard window = new Dashboard();
            window.show();
            this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked
    public void TrainTableDetails(){
        
        try {
            Connection db = DbConnector.getConnection();
            Statement sql = db.createStatement();
            ResultSet rs = sql.executeQuery("select trainNumber,trainName from trainlist order by  trainNumber ASC");
            
            while (rs.next()){
                int trainNumber = rs.getInt("TrainNumber");
                String trainName = rs.getString("TrainName");
                Object[] row = {trainNumber,trainName};
                model = (DefaultTableModel)tblTrainSearch1.getModel();
                model.addRow(row);
                
                
            }
            
            
        } 
        catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    public void clearTrainAvailable(){
        DefaultTableModel model = (DefaultTableModel)tblAvailability.getModel();
        model.setRowCount(0);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JPanel PanelReservation;
    private javax.swing.JPanel PanelSchedule;
    private javax.swing.JPanel PanelTrains;
    private necesario.RSMaterialButtonCircle btnAvailabilityReset;
    private necesario.RSMaterialButtonCircle btnCheckAvailability;
    private necesario.RSMaterialButtonCircle btnReservation;
    private necesario.RSMaterialButtonCircle btnReservationCancel;
    private com.toedter.calendar.JDateChooser dateScheduleDate1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblACTicketFair;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblGeneralTicketFair;
    private javax.swing.JLabel lblTotalFair;
    private rojeru_san.complementos.RSTableMetro tblAvailability;
    private rojeru_san.complementos.RSTableMetro tblTrainSearch1;
    private app.bolivia.swing.JCTextField txtBookedDate;
    private app.bolivia.swing.JCTextField txtReservationNoOfACTickets;
    private app.bolivia.swing.JCTextField txtReservationNoOfGeneralTickets;
    private app.bolivia.swing.JCTextField txtReservationTrainNumber1;
    private app.bolivia.swing.JCTextField txtReservePassengerName;
    private app.bolivia.swing.JCTextField txtReservePassengerPhone;
    private app.bolivia.swing.JCTextField txtTrainNumber;
    private javax.swing.JLabel txtUserShowName;
    // End of variables declaration//GEN-END:variables
}
